#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>


// Forward declaration of the UI class generated by uic
QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class MainWindow : public QMainWindow {
    Q_OBJECT

public:
    explicit MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private:
    Ui::MainWindow *ui;  // Pointer to the UI class
};

#endif // MAINWINDOW_H